import React, { createContext, useContext, useState, useEffect } from 'react';

const ThemeContext = createContext();

export const PRESETS = {
    dark: {
        name: 'Oscuro',
        '--wa-bg-app': '#161717',
        '--wa-bg-sidebar': '#161717',
        '--wa-bg-panel': '#202c33',
        '--wa-bg-chat': '#0b141a',
        '--wa-bg-input': '#2a3942',
        '--wa-bg-bubble-me': '#005c4b',
        '--wa-bg-bubble-them': '#202c33',
        '--wa-bg-nav': '#1d1f1f',
        '--wa-bg-hover': '#2a3942',
        '--wa-bg-active': '#2a3942',
        '--wa-bg-dropdown': '#233138',
        '--wa-bg-header': '#161717',
        '--wa-bg-quick': '#1d1f1f',
        '--wa-bg-side-panel': '#111b21',
        '--wa-bg-side-header': '#202c33',
        '--wa-text-primary': '#e9edef',
        '--wa-text-secondary': '#8696a0',
        '--wa-text-name': '#e9edef',
        '--wa-green': '#00a884',
        '--wa-green-badge': '#00a884',
        '--wa-green-online': '#25d366',
        '--wa-border': '#222d34',
        '--wa-border-input': '#2a3942',
        '--wa-nav-border': '#1d1f1f',
        '--wa-search-border': 'transparent',
        '--wa-card-border': '#2f3b44',
        '--wa-divider': '#2a3942',
        '--wa-green-action': '#00a884',
        '--wa-green-soft': '#103529',
        '--wa-searchbar': '#2d2e2e',
        '--wa-nav-icon-color': '#8696a0',
        '--wa-nav-icon-active': '#00a884',
        '--wa-tick-sent': '#8696a0',
        '--wa-tick-read': '#53bdeb',
        '--wa-doodles': 'url("/images/Doodles-oscuro.jpg")',
        '--wa-community': "url('/images/community-dark.png')",
        '--wa-pc': "url('/images/pc-phone.png')",
        '--wa-doodles-opacity': '0.07',
        '--wa-doodles-invert': '0',
        '--border-color': '#222d34',
        '--border': '#222d34',
        '--text-primary': '#e9edef',
        '--text-secondary': '#8696a0',
        '--hover-effect': '#2a3942',
        '--main-gray': '#111b21',
        '--white': '#ffffff',
        '--text-dark': '#242626',
        '--wa-bubbles-user': '#005c4b',
        '--wa-bubbles-crack': '#202c33',
        '--wa-panel-bg': '#202c33',
        '--wa-dark-bg': '#0b141a',
        '--wa-input-bg': '#2a3942',
    },

    light: {
        name: 'Claro',
        '--wa-bg-app': '#f7f5f2',
        '--wa-bg-sidebar': '#ffffff',
        '--wa-bg-panel': '#ffffff',
        '--wa-bg-chat': '#efeae2',
        '--wa-bg-input': '#f0f2f5',
        '--wa-bg-bubble-me': '#d9fdd3',
        '--wa-bg-bubble-them': '#ffffff',
        '--wa-bg-nav': '#f7f5f3',
        '--wa-bg-hover': '#f5f6f6',
        '--wa-bg-active': '#e9edef',
        '--wa-bg-dropdown': '#ffffff',
        '--wa-bg-header': '#f7f5f2',
        '--wa-bg-quick': '#f0edeb',
        '--wa-bg-side-panel': '#ffffff',
        '--wa-bg-side-header': '#f7f5f2',
        '--wa-text-primary': '#111b21',
        '--wa-text-secondary': '#667781',
        '--wa-text-name': '#111b21',
        '--wa-green': '#00a884',
        '--wa-green-badge': '#25d366',
        '--wa-green-online': '#25d366',
        '--wa-border': '#e9edef',
        '--wa-border-input': '#d1d7db',
        '--wa-nav-border': '#e9edef',
        '--wa-search-border': '#d1d7db',
        '--wa-card-border': '#e9edef',
        '--wa-divider': '#d1d7db',
        '--wa-green-action': '#00a884',
        '--wa-green-soft': '#d9fdd3',
        '--wa-searchbar': '#f0f2f5',
        '--wa-nav-icon-color': '#54656f',
        '--wa-nav-icon-active': '#00a884',
        '--wa-tick-sent': '#667781',
        '--wa-tick-read': '#53bdeb',
        '--wa-doodles': 'url("https://user-images.githubusercontent.com/15075759/28719144-86dc0f70-73b1-11e7-911d-60d70fcded21.png")',
        '--wa-community': "url('/images/community-light.png')",
        '--wa-pc': "url('/images/pc-phone-light.png')",
        '--wa-doodles-opacity': '0.15',
        '--wa-doodles-invert': '1',
        '--border-color': '#e9edef',
        '--border': '#e9edef',
        '--text-primary': '#111b21',
        '--text-secondary': '#667781',
        '--hover-effect': '#f5f6f6',
        '--main-gray': '#fcf5eb',
        '--white': '#ffffff',
        '--text-dark': '#f0edeb',
        '--wa-bubbles-user': '#d9fdd3',
        '--wa-bubbles-crack': '#ffffff',
        '--wa-panel-bg': '#f7f5f2',
        '--wa-dark-bg': '#efeae2',
        '--wa-input-bg': '#f0f2f5',
    },

    teal: {
        name: 'Verde azulado',
        '--wa-bg-app': '#0d1f1c',
        '--wa-bg-sidebar': '#0d1f1c',
        '--wa-bg-panel': '#133028',
        '--wa-bg-chat': '#07120f',
        '--wa-bg-input': '#1a3530',
        '--wa-bg-bubble-me': '#00665a',
        '--wa-bg-bubble-them': '#133028',
        '--wa-bg-nav': '#0a1a17',
        '--wa-bg-hover': '#1a3530',
        '--wa-bg-active': '#1a3530',
        '--wa-bg-dropdown': '#133028',
        '--wa-bg-header': '#0a1a17',
        '--wa-bg-quick': '#0a1a17',
        '--wa-bg-side-panel': '#0d1f1c',
        '--wa-bg-side-header': '#133028',
        '--wa-text-primary': '#d4edea',
        '--wa-text-secondary': '#7fb5ae',
        '--wa-text-name': '#d4edea',
        '--wa-green': '#06d6a0',
        '--wa-green-badge': '#06d6a0',
        '--wa-green-online': '#06d6a0',
        '--wa-border': '#1a3530',
        '--wa-border-input': '#1a3530',
        '--wa-nav-border': '#1a3530',
        '--wa-search-border': 'transparent',
        '--wa-card-border': '#1a3530',
        '--wa-divider': '#1a3530',
        '--wa-green-action': '#06d6a0',
        '--wa-green-soft': '#0d2e28',
        '--wa-searchbar': '#1a3530',
        '--wa-nav-icon-color': '#7fb5ae',
        '--wa-nav-icon-active': '#06d6a0',
        '--wa-tick-sent': '#7fb5ae',
        '--wa-tick-read': '#06d6a0',
        '--wa-doodles': 'url("https://user-images.githubusercontent.com/15075759/28719144-86dc0f70-73b1-11e7-911d-60d70fcded21.png")',
        '--wa-doodles-opacity': '0.05',
        '--wa-doodles-invert': '0',
        '--border-color': '#1a3530',
        '--border': '#1a3530',
        '--text-primary': '#d4edea',
        '--text-secondary': '#7fb5ae',
        '--hover-effect': '#1a3530',
        '--main-gray': '#0d1f1c',
        '--white': '#ffffff',
        '--text-dark': '#133028',
        '--wa-bubbles-user': '#00665a',
        '--wa-bubbles-crack': '#133028',
        '--wa-panel-bg': '#133028',
        '--wa-dark-bg': '#07120f',
        '--wa-input-bg': '#1a3530',
    },

    midnight: {
        name: 'Medianoche',
        '--wa-bg-app': '#0a0a0f',
        '--wa-bg-sidebar': '#0e0e1a',
        '--wa-bg-panel': '#16162a',
        '--wa-bg-chat': '#070712',
        '--wa-bg-input': '#1c1c35',
        '--wa-bg-bubble-me': '#2d2b8a',
        '--wa-bg-bubble-them': '#16162a',
        '--wa-bg-nav': '#0a0a14',
        '--wa-bg-hover': '#1c1c35',
        '--wa-bg-active': '#1c1c35',
        '--wa-bg-dropdown': '#16162a',
        '--wa-bg-header': '#0a0a14',
        '--wa-bg-quick': '#0e0e1a',
        '--wa-bg-side-panel': '#0a0a0f',
        '--wa-bg-side-header': '#16162a',
        '--wa-text-primary': '#dddff7',
        '--wa-text-secondary': '#7b7da8',
        '--wa-text-name': '#dddff7',
        '--wa-green': '#818cf8',
        '--wa-green-badge': '#818cf8',
        '--wa-green-online': '#818cf8',
        '--wa-border': '#1c1c35',
        '--wa-border-input': '#1c1c35',
        '--wa-nav-border': '#1c1c35',
        '--wa-search-border': 'transparent',
        '--wa-card-border': '#1c1c35',
        '--wa-divider': '#1c1c35',
        '--wa-green-action': '#818cf8',
        '--wa-green-soft': '#1c1c35',
        '--wa-searchbar': '#1c1c35',
        '--wa-nav-icon-color': '#7b7da8',
        '--wa-nav-icon-active': '#818cf8',
        '--wa-tick-sent': '#7b7da8',
        '--wa-tick-read': '#818cf8',
        '--wa-doodles': 'url("https://user-images.githubusercontent.com/15075759/28719144-86dc0f70-73b1-11e7-911d-60d70fcded21.png")',
        '--wa-doodles-opacity': '0.04',
        '--wa-doodles-invert': '0',
        '--border-color': '#1c1c35',
        '--border': '#1c1c35',
        '--text-primary': '#dddff7',
        '--text-secondary': '#7b7da8',
        '--hover-effect': '#1c1c35',
        '--main-gray': '#0a0a0f',
        '--white': '#ffffff',
        '--text-dark': '#16162a',
        '--wa-bubbles-user': '#2d2b8a',
        '--wa-bubbles-crack': '#16162a',
        '--wa-panel-bg': '#16162a',
        '--wa-dark-bg': '#070712',
        '--wa-input-bg': '#1c1c35',
    },

    rose: {
        name: 'Rosa',
        '--wa-bg-app': '#1a0d12',
        '--wa-bg-sidebar': '#1a0d12',
        '--wa-bg-panel': '#2a1520',
        '--wa-bg-chat': '#0f070b',
        '--wa-bg-input': '#2a1520',
        '--wa-bg-bubble-me': '#8b1a4a',
        '--wa-bg-bubble-them': '#2a1520',
        '--wa-bg-nav': '#130a0e',
        '--wa-bg-hover': '#2a1520',
        '--wa-bg-active': '#2a1520',
        '--wa-bg-dropdown': '#2a1520',
        '--wa-bg-header': '#130a0e',
        '--wa-bg-quick': '#130a0e',
        '--wa-bg-side-panel': '#1a0d12',
        '--wa-bg-side-header': '#2a1520',
        '--wa-text-primary': '#f5d0de',
        '--wa-text-secondary': '#b07090',
        '--wa-text-name': '#f5d0de',
        '--wa-green': '#f472b6',
        '--wa-green-badge': '#f472b6',
        '--wa-green-online': '#f472b6',
        '--wa-border': '#3d1a28',
        '--wa-border-input': '#3d1a28',
        '--wa-nav-border': '#3d1a28',
        '--wa-search-border': 'transparent',
        '--wa-card-border': '#3d1a28',
        '--wa-divider': '#3d1a28',
        '--wa-green-action': '#f472b6',
        '--wa-green-soft': '#3d1a28',
        '--wa-searchbar': '#2a1520',
        '--wa-nav-icon-color': '#b07090',
        '--wa-nav-icon-active': '#f472b6',
        '--wa-tick-sent': '#b07090',
        '--wa-tick-read': '#f472b6',
        '--wa-doodles': 'url("https://user-images.githubusercontent.com/15075759/28719144-86dc0f70-73b1-11e7-911d-60d70fcded21.png")',
        '--wa-doodles-opacity': '0.04',
        '--wa-doodles-invert': '0',
        '--border-color': '#3d1a28',
        '--border': '#3d1a28',
        '--text-primary': '#f5d0de',
        '--text-secondary': '#b07090',
        '--hover-effect': '#2a1520',
        '--main-gray': '#1a0d12',
        '--white': '#ffffff',
        '--text-dark': '#2a1520',
        '--wa-bubbles-user': '#8b1a4a',
        '--wa-bubbles-crack': '#2a1520',
        '--wa-panel-bg': '#2a1520',
        '--wa-dark-bg': '#0f070b',
        '--wa-input-bg': '#2a1520',
    },
};

// Aplica el preset 
export const applyTheme = (preset) => {
    const root = document.documentElement;
    Object.entries(preset).forEach(([key, val]) => {
        if (key !== 'name') root.style.setProperty(key, val);
    });
};

export const ThemeProvider = ({ children }) => {
    const [themeName, setThemeName] = useState(
        () => localStorage.getItem('cracks_theme') || 'dark'
    );
    const [customColors, setCustomColors] = useState(() => {
        try {
            const s = localStorage.getItem('cracks_custom_colors');
            return s ? JSON.parse(s) : {};
        } catch { return {}; }
    });

    useEffect(() => {
        const base = PRESETS[themeName] || PRESETS.dark;
        applyTheme({ ...base, ...customColors });
        localStorage.setItem('cracks_theme', themeName);
    }, [themeName, customColors]);

    const setTheme = (name) => {
        setThemeName(name);
        setCustomColors({});
        localStorage.removeItem('cracks_custom_colors');
    };

    const setCustomColor = (varName, value) => {
        const updated = { ...customColors, [varName]: value };
        setCustomColors(updated);
        localStorage.setItem('cracks_custom_colors', JSON.stringify(updated));
        document.documentElement.style.setProperty(varName, value);
    };

    return (
        <ThemeContext.Provider value={{ themeName, setTheme, customColors, setCustomColor, presets: PRESETS }}>
            {children}
        </ThemeContext.Provider>
    );
};

export const useTheme = () => useContext(ThemeContext);